spring.application.name=try-Mybatis3
server.port=8082

#postgre 설정
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5433/hrd
spring.datasource.url=jdbc:postgresql://localhost:5433/hrd?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=1234

#MyBatis 설정
#mybatis.mapper-locations=classpath:mapper/*.xml

## configfile
mybatis.config-location=classpath:mybatis/mybatis-config.xml

## Mapperfile_쿼리문 작성
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml