spring.application.name=try-Mybatis1
server.port=8082

#postgre 설정
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/hrd
spring.datasource.username=postgres
spring.datasource.password=pgadmin

#MyBatis 설정
mybatis.mapper-locations=classpath:mapper/*.xml